name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  Test:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          CGO_ENABLED=1 go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic -tags=memdb,goleveldb,cleveldb,boltdb,rocksdb,badgerdb,pebbledb -v
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: true  


  Pebble:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
  
  Pebble2:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
  
  Pebble3:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
  Pebble4:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
      runs-on: ubuntu-latest
      container: tendermintdev/docker-tm-db-testing
      steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
  Pebble5:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
      runs-on: ubuntu-latest
      container: tendermintdev/docker-tm-db-testing
      steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
  Pebble6:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
  Pebble7:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
          
  Pebble8:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
  Pebble9:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
  Pebble10:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$
          
          
  Pebble11:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$


  Pebble12:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$


  Pebble13:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$

  Pebble14:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$


  Pebble15:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$

  Pebble16:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$


  Pebble17:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$

  Pebble18:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$

  Pebble19:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$


  Pebble20:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          go test -count 5000 -tags pebbledb -test.run ^TestDBIterator/pebbledb$